/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Lb2Component {
        "break": number;
        "icon": string;
        "image": string;
        "lung": number;
        "maxValue": number;
        "name": string;
        "value": number;
    }
    interface Lb2ComponentHd {
        "break": number;
        "image": string;
        "lung": number;
        "maxValue": number;
        "name": string;
        "value": number;
    }
    interface Lb2SimpleText {
        "color": string;
        "name": string;
        "value": number;
    }
}
declare global {
    interface HTMLLb2ComponentElement extends Components.Lb2Component, HTMLStencilElement {
    }
    var HTMLLb2ComponentElement: {
        prototype: HTMLLb2ComponentElement;
        new (): HTMLLb2ComponentElement;
    };
    interface HTMLLb2ComponentHdElement extends Components.Lb2ComponentHd, HTMLStencilElement {
    }
    var HTMLLb2ComponentHdElement: {
        prototype: HTMLLb2ComponentHdElement;
        new (): HTMLLb2ComponentHdElement;
    };
    interface HTMLLb2SimpleTextElement extends Components.Lb2SimpleText, HTMLStencilElement {
    }
    var HTMLLb2SimpleTextElement: {
        prototype: HTMLLb2SimpleTextElement;
        new (): HTMLLb2SimpleTextElement;
    };
    interface HTMLElementTagNameMap {
        "lb2-component": HTMLLb2ComponentElement;
        "lb2-component-hd": HTMLLb2ComponentHdElement;
        "lb2-simple-text": HTMLLb2SimpleTextElement;
    }
}
declare namespace LocalJSX {
    interface Lb2Component {
        "break"?: number;
        "icon"?: string;
        "image"?: string;
        "lung"?: number;
        "maxValue"?: number;
        "name"?: string;
        "value"?: number;
    }
    interface Lb2ComponentHd {
        "break"?: number;
        "image"?: string;
        "lung"?: number;
        "maxValue"?: number;
        "name"?: string;
        "value"?: number;
    }
    interface Lb2SimpleText {
        "color"?: string;
        "name"?: string;
        "value"?: number;
    }
    interface IntrinsicElements {
        "lb2-component": Lb2Component;
        "lb2-component-hd": Lb2ComponentHd;
        "lb2-simple-text": Lb2SimpleText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lb2-component": LocalJSX.Lb2Component & JSXBase.HTMLAttributes<HTMLLb2ComponentElement>;
            "lb2-component-hd": LocalJSX.Lb2ComponentHd & JSXBase.HTMLAttributes<HTMLLb2ComponentHdElement>;
            "lb2-simple-text": LocalJSX.Lb2SimpleText & JSXBase.HTMLAttributes<HTMLLb2SimpleTextElement>;
        }
    }
}
