/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Lb2Component {
        "break": number;
        "icon": string;
        "lung": number;
        "maxValue": number;
        "name": string;
        "value": number;
    }
    interface Lb2Component2 {
        "name": string;
    }
}
declare global {
    interface HTMLLb2ComponentElement extends Components.Lb2Component, HTMLStencilElement {
    }
    var HTMLLb2ComponentElement: {
        prototype: HTMLLb2ComponentElement;
        new (): HTMLLb2ComponentElement;
    };
    interface HTMLLb2Component2Element extends Components.Lb2Component2, HTMLStencilElement {
    }
    var HTMLLb2Component2Element: {
        prototype: HTMLLb2Component2Element;
        new (): HTMLLb2Component2Element;
    };
    interface HTMLElementTagNameMap {
        "lb2-component": HTMLLb2ComponentElement;
        "lb2-component2": HTMLLb2Component2Element;
    }
}
declare namespace LocalJSX {
    interface Lb2Component {
        "break"?: number;
        "icon"?: string;
        "lung"?: number;
        "maxValue"?: number;
        "name"?: string;
        "value"?: number;
    }
    interface Lb2Component2 {
        "name"?: string;
    }
    interface IntrinsicElements {
        "lb2-component": Lb2Component;
        "lb2-component2": Lb2Component2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lb2-component": LocalJSX.Lb2Component & JSXBase.HTMLAttributes<HTMLLb2ComponentElement>;
            "lb2-component2": LocalJSX.Lb2Component2 & JSXBase.HTMLAttributes<HTMLLb2Component2Element>;
        }
    }
}
